[package]
name = "vexide-core"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Core functionality for vexide"
keywords = ["PROS", "Robotics", "bindings", "vex", "v5"]
categories = [
    "api-bindings",
    "no-std",
    "science::robotics",
]
repository = "https://github.com/vexide/vexide"
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
    "Tropical"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vex-sdk = "0.12.0"
embedded-io-async = { version = "0.6.1", features = ["alloc"] }
snafu = { version = "0.8.0", default-features = false, features = [
    "rust_1_61",
    "unstable-core-error",
] }
talc = "4.3.1"
lock_api = "0.4.11"
critical-section = { version = "1.1.2", features = ["restore-state-bool"] }
bitflags = "2.4.2"
futures-core = { version = "0.3.30", default-features = false, features = ["alloc"] }
pin-project = "1.1.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
dlmalloc = { version = "0.2.4", features = ["global"] }

[lints]
workspace = true
