[package]
name = "vexide-math"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Commonly used mathematical formulas for vexide"
keywords = ["Robotics", "vex", "v5"]
categories = [
    "no-std",
    "science::robotics",
    "Mathematics",
]
repository = "https://github.com/vexide/vexide"
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
    "Tropical"
]

[dependencies]
num = { version = "0.4.1", default-features = false }
vexide-core = { version = "0.2.0", path = "../vexide-core" }

[lints]
workspace = true
